MSSProject.Web/Areas/Admin/Pages/AdminUser/ComplaintManagement.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MSSProject.Data.Models;
using MSSProject.Web.Areas.Core.Data;
using MSSProject.Web.Areas.Identity.Data;
using MSSProject.Web.Data;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;

namespace MSSProject.Web.Areas.Admin.Pages.AdminUser
{

    [Authorize(Roles = "Administrator")]
    public class ComplaintManagementModel : DI_BasePageModel
    {
        public ComplaintManagementModel(MSSCoreDbContext context,
            IAuthorizationService authorizationService,
            UserManager<MSSWebUser> userManager,
            RoleManager<IdentityRole> roleManager,
            MSSWebAuthContext authContext) : base(context,
                                                        authorizationService,
                                                        userManager,
                                                        roleManager,
                                                        authContext)
        { }
        [BindProperty]
        public Complaint Complaint { get; set; }
        public IList<Complaint> ComplaintList { get; set; }

        [BindProperty, MaxLength(300)]
        public string AdminResponse { get; set; }
        public async Task<IActionResult> OnGetAsync()
        {
            ComplaintList = await Context.Complaints
                .AsNoTracking()
                .ToListAsync();

            if (ComplaintList == null)
            {
                return NotFound();
            }
            return Page();
        }
        public async Task<IActionResult> OnPostAddResponseAsync(int compId)
        {
            var response = AdminResponse;
            var complaint = await Context.Complaints.FindAsync(compId);
            if (response != complaint.Response)
            {
                complaint.Response = response;
            }
            complaint.AdminStatus = ComplaintStatus.ResponseCompleted;
            if (Complaint == null)
            {
                return NotFound();
            }

            Context.Update(complaint);
            await Context.SaveChangesAsync();

            return Redirect("./ComplaintManagement");
        }
    }
}

MSSProject.Web/Areas/Admin/Pages/AdminUser/CoreFunctions.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MSSProject.Web.Areas.Admin.Pages.AdminUser
{
    [Authorize(Roles = "Administrator")]
    public class CoreFunctionsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

MSSProject.Web/Areas/Admin/Pages/AdminUser/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using MSSProject.Web.Areas.Core.Data;
using MSSProject.Web.Areas.Identity.Data;
using MSSProject.Web.Data;

namespace MSSProject.Web.Areas.Admin.Pages.AdminUser
{
    [Authorize(Roles = "Administrator")]
    public class IndexModel : DI_BasePageModel
    {
        public IndexModel(MSSCoreDbContext context,
            IAuthorizationService authorizationService,
            UserManager<MSSWebUser> userManager,
            RoleManager<IdentityRole> roleManager,
            MSSWebAuthContext authContext) : base(context,
                                                          authorizationService,
                                                          userManager,
                                                          roleManager,
                                                          authContext)
        { }
        public void OnGet()
        {
        }
    }
}

MSSProject.Web/Areas/Admin/Pages/AdminUser/MeetingManagement.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MSSProject.Data.Models;
using MSSProject.Web.Areas.Core.Data;
using MSSProject.Web.Areas.Identity.Data;
using MSSProject.Web.Data;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace MSSProject.Web.Areas.Admin.Pages.AdminUser
{
    [Authorize(Roles = "Administrator")]
    public class MeetingManagementModel : DI_BasePageModel
    {
        public MeetingManagementModel(MSSCoreDbContext context,
           IAuthorizationService authorizationService,
           UserManager<MSSWebUser> userManager,
           RoleManager<IdentityRole> roleManager,
           MSSWebAuthContext authContext) : base(context,
                                                         authorizationService,
                                                         userManager,
                                                         roleManager,
                                                         authContext)
        { }
        [BindProperty]
        public Meeting Meeting { get; set; }
        [BindProperty]
        public IList<Room> RoomList { get; set; }
        [BindProperty]
        public IList<Meeting> MeetingList { get; set; }
        [BindProperty]
        public IList<MSSWebUser> UserList { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            UserList = await AuthContext.Users
                .AsNoTracking()
                .ToListAsync();
            MeetingList = await Context.Meetings
                .AsNoTracking()
                .ToListAsync();

            return Page();
        }

        public async Task<IActionResult> OnPostDeleteMeeting(int meetId)
        {
            Meeting = await Context.Meetings.FindAsync(meetId);
            Context.Meetings.Remove(Meeting);
            await Context.SaveChangesAsync();

            return Redirect("./MeetingManagement");
        }
    }
}

MSSProject.Web/Areas/Admin/Pages/AdminUser/RoomManagement.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MSSProject.Data.Models;
using MSSProject.Web.Areas.Core.Data;
using MSSProject.Web.Areas.Identity.Data;
using MSSProject.Web.Data;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace MSSProject.Web.Areas.Admin.Pages.AdminUser
{
    [Authorize(Roles = "Administrator")]
    public class RoomManagementModel : DI_BasePageModel
    {
        public RoomManagementModel(MSSCoreDbContext context,
            IAuthorizationService authorizationService,
            UserManager<MSSWebUser> userManager,
            RoleManager<IdentityRole> roleManager,
            MSSWebAuthContext authContext) : base(context,
                                                          authorizationService,
                                                          userManager,
                                                          roleManager,
                                                          authContext)
        { }
        [BindProperty]
        public Room Room { get; set; }
        public IList<Room> RoomList { get; set; }
        public IList<Meeting> MeetingList { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            MeetingList = await Context.Meetings
                .AsNoTracking()
                .ToListAsync();
            RoomList = await Context.Rooms
                .AsNoTracking()
                .ToListAsync();

            if (RoomList == null)
            {
                return NotFound();
            }
            return Page();
        }
        public async Task<IActionResult> OnPostChangeAsync(int id)
        {
            var roomToUpdate = await Context.Rooms.FindAsync(id);

            if (roomToUpdate == null)
            {
                return NotFound();
            }
            if (roomToUpdate.Availability == Availability.Available)
            {
                roomToUpdate.Availability = Availability.Unavailable;
                Context.Update(roomToUpdate);
                await Context.SaveChangesAsync();
            }
            else
            {
                roomToUpdate.Availability = Availability.Available;
                Context.Update(roomToUpdate);
                await Context.SaveChangesAsync();
            }
            return Redirect("./RoomManagement");
        }
    }
}

MSSProject.Web/Areas/Admin/Pages/AdminUser/UserManagement.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MSSProject.Web.Areas.Core.Data;
using MSSProject.Web.Areas.Identity.Data;
using MSSProject.Web.Data;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace MSSProject.Web.Areas.Admin.Pages.AdminUser
{
    [Authorize(Roles = "Administrator")]
    public class UserManagementModel : DI_BasePageModel
    {
        public UserManagementModel(MSSCoreDbContext context,
            IAuthorizationService authorizationService,
            UserManager<MSSWebUser> userManager,
            RoleManager<IdentityRole> roleManager,
            MSSWebAuthContext authContext) : base(context,
                                                        authorizationService,
                                                        userManager,
                                                        roleManager,
                                                        authContext)
        { }
        public IList<MSSWebUser> UserList { get; set; }
        public async Task<IActionResult> OnGetAsync()
        {
            UserList = await AuthContext.Users.AsNoTracking().ToListAsync();
            if (UserList == null)
            {
                return NotFound();
            }
            return Page();
        }
        public async Task<IActionResult> OnPostAddAdmin(string id)
        {
            var userToUpdate = await UserManager.FindByIdAsync(id);
            if (userToUpdate == null)
            {
                return NotFound();
            }
            if (await UserManager.IsInRoleAsync(userToUpdate, "Administrator") == false)
            {
                await UserManager.RemoveFromRoleAsync(userToUpdate, "StandardUser");
                await UserManager.AddToRoleAsync(userToUpdate, "Administrator");
                await AuthContext.SaveChangesAsync();
            }
            else
            {
                await UserManager.RemoveFromRoleAsync(userToUpdate, "Administrator");
                await UserManager.AddToRoleAsync(userToUpdate, "StandardUser");
                await AuthContext.SaveChangesAsync();
            }
            return Redirect("./UserManagement");
        }
    }
}

MSSProject.Web/Areas/Admin/Pages/AdminUser/ComplaintManagement.cshtml
@page
@model MSSProject.Web.Areas.Admin.Pages.AdminUser.ComplaintManagementModel
@{
    ViewData["Title"] = "Complaint Management";
    ViewData["ActivePage"] = AdminHubNavPages.ComplaintManagement;
}
<h4 class="text-center">@ViewData["Title"]</h4>

<h5 class="text-center mt-5" style="color: white">
    Awaiting Response
</h5>
    <table class="table-bordered w-100 text-center">
        <tr style="color:white">
            <th scope="col">Name</th>
            <th scope="col">Date</th>
            <th scope="col">Complaint</th>
            <th scope="col">Response</th>
            <th scope="col"></th>
        </tr>
        @foreach (var complaint in Model.ComplaintList)
        {
            if (complaint.AdminStatus == MSSProject.Data.Models.ComplaintStatus.Incomplete)
            {
                <tr style="background-color: #185895; color: white">
                    <td>@Html.Encode(complaint.CreatorName)</td>
                    <td>@Html.Encode(complaint.DateCreated)</td>
                    <td class="text-left w-50" style="font-size:small">@Html.Encode(complaint.ComplaintText)</td>
                    <td class="w-25">
                        <form asp-page-handler="addresponse" method="post">
                            <textarea class="form-control" id="response" rows="2" asp-for="AdminResponse" style="font-size:small"></textarea>
                            <button type="submit" class="btn m-1">Respond</button>
                            <input type="hidden" name="compId" value="@complaint.CompId"  />
                        </form>
                    </td>
                </tr>
            }
        }
    </table>
<h5 class="text-center mt-5" style="color: white">
    Completed Responses
</h5>
<table class="table-bordered w-100 text-center">
    <tr style="color: white">
        <th scope="col">Name</th>
        <th scope="col">Date Created</th>
        <th scope="col">Complaint</th>
        <th scope="col">Complaint ID</th>
        <th scope="col">Response</th>
    </tr>
    @foreach (var complaint in Model.ComplaintList)
    {
        if (complaint.AdminStatus == MSSProject.Data.Models.ComplaintStatus.ResponseCompleted)
        {
            <tr style="background-color: #185895; color: white">
                <td>@Html.Encode(complaint.CreatorName)</td>
                <td>@Html.Encode(complaint.DateCreated)</td>
                <td class="text-left w-50" style="font-size:small">@Html.Encode(complaint.ComplaintText)</td>
                <td>@Html.Encode(complaint.CompId)</td>
                <td class="text-left" style="font-size: small">@Html.Encode(complaint.Response)</td>
            </tr>
        }
    }
</table>

MSSProject.Web/Areas/Admin/Pages/AdminUser/CoreFunctions.cshtml
@page
@model MSSProject.Web.Areas.Admin.Pages.AdminUser.CoreFunctionsModel
@{
    ViewData["Title"] = "Navigate to Standard User Functions";
    ViewData["ActivePage"] = AdminHubNavPages.CoreFunctions;
}

<h4 class="mt-4 text-center mx-auto">@ViewData["Title"]</h4>

<div class="shadow p-4 mt-5 text-center w-50 rounded-pill mx-auto background_col_1">
    <a id="manage" class="nav-link btn btn-link mx-auto rounded-pill w-75 " asp-area="Core" asp-page="/User/Index" title="Core Hub">Standard User Functions</a>
</div>

MSSProject.Web/Areas/Admin/Pages/AdminUser/Index.cshtml
@page
@model MSSProject.Web.Areas.Admin.Pages.AdminUser.IndexModel
@{
    ViewData["Title"] = "Administrator Hub";
    ViewData["ActivePage"] = AdminHubNavPages.Index;
}


<div class="text-center col-lg">
    <img src="~/images/MainLogo_Trans.png" alt="PennStateSoft" />
</div>

MSSProject.Web/Areas/Admin/Pages/AdminUser/MeetingManagement.cshtml
@page
@using Microsoft.AspNetCore.Identity
@using MSSProject.Web.Areas.Identity.Data
@model MSSProject.Web.Areas.Admin.Pages.AdminUser.MeetingManagementModel
@{
    ViewData["Title"] = "Meeting Management";
    ViewData["ActivePage"] = AdminHubNavPages.MeetingManagement;
}
@inject UserManager<MSSWebUser> UserManager
@inject MSSCoreDbContext dbContext

<h4 class="text-center">@ViewData["Title"]</h4>
<hr />
<div>

</div>
<div>
    @if (Model.MeetingList == null)
    {
        <div class="container rounded shadow-lg p-3 mt-3" style="background-color:#185895">
            <h3 class="text-center" style="color:white">No Meetings Scheduled</h3>
        </div>
    }
    else
    {
        <h3 class="text-center mb-3" style="color:white">Current Meetings Scheduled</h3>
        <table class="table-bordered w-100 text-center">
            <tr style="color:white">
                <th scope="col">Facilitator</th>
                <th scope="col">Date and Time</th>
                <th scope="col">Room</th>
                <th scope="col">Special Room</th>
                <th scope="col">Cost</th>
                <th scope="col">Participants</th>
                <th scope="col">Options</th>
            </tr>
            @foreach (var meeting in Model.MeetingList)
            {
                var fac = await UserManager.FindByNameAsync(meeting.OwnerId);
                var room = dbContext.Rooms.Find(meeting.RoomId);
                var facName = fac.FirstName + " " + fac.LastName;
                <tr style="background-color: #185895; color:white">
                    <td>@Html.Encode(facName)</td>
                    <td>@Html.Encode(meeting.MeetDateTime)</td>
                    <td>@Html.Encode(room.RoomName)</td>
                    <td>@Html.Encode(room.SpecialRoom)</td>
                    <td>$@Html.Encode(room.Cost)</td>
                    @{
                        if (meeting.ParticipantList == null)
                        {
                            <td>No Participants</td>
                        }
                        else
                        {
                            foreach (var participant in meeting.ParticipantList)
                            {
                                <td>@Html.Encode(participant)</td>
                            }
                        }
                    }
                    <td>
                        <form asp-page-handler="deletemeeting" method="post">
                            <button type="submit" class="btn m-1">Delete</button>
                            <input type="hidden" name="meetId" value="@meeting.MeetId" />
                        </form>
                    </td>
                </tr>
            }
        </table>
    }
</div>

MSSProject.Web/Areas/Admin/Pages/AdminUser/RoomManagement.cshtml
@page
@model RoomManagementModel
@{
    ViewData["Title"] = "Room Management";
    ViewData["ActivePage"] = AdminHubNavPages.RoomManagement;
}

<h4 class="text-center mb-3">@ViewData["Title"]</h4>

<p class="text-center mb-3">To change room availability, press "Change Availability" button.</p>
<div class="d-flex justify-content-around flex-wrap">
    @foreach (var room in Model.RoomList)
    {
        <div class="card text-center mb-4 shadow-lg" id="@room.RoomId" style="width: 13rem; height: 15rem; background-color: #185895;">
            <h5 class="card-header" style="background-color: #185895; color: white;">@Html.Encode(room.RoomName)</h5>
            <div class="card-body" style="background-color: #6D9CCA;">
                <h5 class="card-text text-white" style="font-size:small">Cost: $@Html.Encode(room.Cost)</h5>
                <h5 class="card-text text-white" style="font-size:small">Special Room: @Html.Encode(room.SpecialRoom)</h5>
                @if (room.Availability == MSSProject.Data.Models.Availability.Available)
                {
                    <h5 class="card-text text-white p-2 rounded" style="background-color: forestgreen">@Html.Encode(room.Availability)</h5>
                }
                else
                {
                    <h5 class="card-text text-white p-2 rounded" style="background-color: red">@Html.Encode(room.Availability)</h5>
                }
                @{
                    int meetingCount = 0;
                    foreach (var meeting in Model.MeetingList)
                    {
                        if (meeting.RoomId == room.RoomId)
                        {
                            meetingCount++;
                        }
                    }
                    <h5 class="card-text text-white" style="font-size:small">Meetings @meetingCount</h5>
                }

            </div>
            <div class="form-group m-1 text-center" style="background-color: #185895;">
                <form asp-page-handler="change" method="post">
                    <button type="submit" class="btn btn-primary">Change Availability</button>
                    <input type="hidden" name="id" value="@room.RoomId" />
                </form>
            </div>
        </div>
    }
</div>

MSSProject.Web/Areas/Admin/Pages/AdminUser/UserManagement.cshtml
@page
@using Microsoft.AspNetCore.Identity
@using MSSProject.Web.Areas.Identity.Data
@model MSSProject.Web.Areas.Admin.Pages.AdminUser.UserManagementModel
@{
    ViewData["Title"] = "User Management";
    ViewData["ActivePage"] = AdminHubNavPages.UserManagement;
}
@inject UserManager<MSSWebUser> UserManager

<h4 class="text-center mb-3">@ViewData["Title"]</h4>

<p class="text-center mb-3">To change user permission to Administrator, press the button.</p>

<table class="table-bordered w-100 text-center">
    <tr style="color: whitesmoke">
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Permissions</th>
        <th scope="col">Manage</th>
    </tr>
    @foreach (var user in Model.UserList)
    {
        var currUser = await UserManager.GetUserAsync(HttpContext.User);
        if (currUser.Id != user.Id)
        {
            <tr style="background-color: #185895; color: white">
                <td>@Html.Encode(user.FirstName + " " + user.LastName)</td>
                <td>@Html.Encode(user.Email)</td>
                @if (await UserManager.IsInRoleAsync(user, "Administrator") == true)
                {
                    <td>Administrator</td>
                }
                else
                {
                    <td>Standard User</td>
                }
                <td>
                    <form asp-page-handler="addadmin" method="post">
                        <button type="submit" class="btn btn-primary m-1">Change Permission</button>
                        <input type="hidden" name="id" value="@user.Id" />
                    </form>
                </td>
            </tr>
        }
    }
</table>

MSSProject.Web/Areas/Admin/Pages/AdminUser/_AdminHubNav.cshtml
<ul class="nav nav-pills mt-5 flex-column">
    <li class="nav-item">
        <a class="nav-link @AdminHubNavPages.IndexNavClass(ViewContext)" id="adminhub" asp-page="./Index">Admin Hub</a>
    </li>
    <li class="nav-item">
        <a class="nav-link @AdminHubNavPages.MeetingManagementNavClass(ViewContext)" id="meetingman" asp-page="./MeetingManagement">Meeting Management</a>
    </li>
    <li class="nav-item">
        <a class="nav-link @AdminHubNavPages.RoomManagementNavClass(ViewContext)" id="roomman" asp-page="./RoomManagement">Room Management</a>
    </li>
    <li class="nav-item">
        <a class="nav-link @AdminHubNavPages.ComplaintManagementNavClass(ViewContext)" id="complaintman" asp-page="./ComplaintManagement">Complaint Management</a>
    </li>
    <li class="nav-item">
        <a class="nav-link @AdminHubNavPages.UserManagementNavClass(ViewContext)" id="userman" asp-page="./UserManagement">User Management</a>
    </li>
    <li class="nav-item">
        <a class="nav-link @AdminHubNavPages.CoreFunctionNavClass(ViewContext)" id="corefunc" asp-page="./CoreFunctions">Standard User Functions</a>
    </li>
</ul>