MSSProject.Web/Models/Complaint.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace MSSProject.Data.Models
{
    public class Complaint
    {
        [Key]
        public int CompId { get; set; }
        public string CreatorId { get; set; }
        public string CreatorName { get; set; }
        public string CreatorEmail { get; set; }
        public DateTime DateCreated { get; set; }
        public string ComplaintText { get; set; }
        public string Response { get; set; }
        public ComplaintStatus AdminStatus { get; set; }
    }
    public enum ComplaintStatus
    {
        ResponseCompleted,
        Incomplete
    }
}

MSSProject.Web/Models/Meeting.cs
using MSSProject.Web.Models;
using System;
using System.Collections.Generic;

namespace MSSProject.Data.Models
{
    public class Meeting
    {
        public int MeetId { get; set; }
        public string OwnerId { get; set; }
        //this is the UserId from AspNetUser table (Identity)
        public int RoomId { get; set; }
        public DateTime MeetDateTime { get; set; }
        public List<Participant> ParticipantList { get; set; }
        public SpecialRoom SpecialRoom { get; set; }
    }
}

MSSProject.Web/Models/PaymentInfo.cs
using System;

namespace MSSProject.Data.Models
{
    public class PaymentInfo
    {
        public int PayId { get; set; }
        public string OwnerId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CardNumber { get; set; }
        public string CardType { get; set; }
        public string Cvv { get; set; }
        public DateTime ExpirationDate { get; set; }
        public string BillingZipCode { get; set; }
    }
}

MSSProject.Web/Areas/Core/Pages/User/AdminFunctions.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MSSProject.Web.Areas.Core.Pages.User
{
    public class AdminFunctionsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

MSSProject.Web/Areas/Core/Pages/User/Complaints.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MSSProject.Data.Models;
using MSSProject.Web.Areas.Core.Data;
using MSSProject.Web.Areas.Identity.Data;
using MSSProject.Web.Data;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;

namespace MSSProject.Web.Areas.Core.Pages.User
{
    [Authorize]
    public class ComplaintsModel : DI_BasePageModel
    {
        public ComplaintsModel(MSSCoreDbContext context,
           IAuthorizationService authorizationService,
           UserManager<MSSWebUser> userManager,
           RoleManager<IdentityRole> roleManager,
           MSSWebAuthContext authContext) : base(context,
                                                         authorizationService,
                                                         userManager,
                                                         roleManager,
                                                         authContext)
        { }
        [BindProperty]
        public Complaint Complaint { get; set; }
        public IList<Complaint> ComplaintList { get; set; }
        [BindProperty]
        public InputModel Input { get; set; }
        public class InputModel
        {
            public string CreatorId { get; set; }
            public string CreatorName { get; set; }
            public string CreatorEmail { get; set; }
            public DateTime DateCreated { get; set; }

            [Required]
            [MaxLength(300)]
            [Display(Name = "complaint text")]
            public string ComplaintText { get; set; }

            public string Response { get; set; }
            public ComplaintStatus AdminStatus { get; set; }
        }
        public async Task<IActionResult> OnGetAsync()
        {
            ComplaintList = await Context.Complaints
                .AsNoTracking()
                .ToListAsync();
            if (ComplaintList == null)
            {
                return NotFound();
            }
            return Page();
        }
        public async Task<IActionResult> OnPostCreateComplaintAsync()
        {
            var user = await UserManager.GetUserAsync(HttpContext.User);
            if (ModelState.IsValid)
            {
                Complaint = new Complaint
                {
                    CreatorId = user.Id,
                    CreatorName = user.FirstName + " " + user.LastName,
                    CreatorEmail = user.Email,
                    DateCreated = DateTime.Now,
                    ComplaintText = Input.ComplaintText,
                    Response = null,
                    AdminStatus = ComplaintStatus.Incomplete
                };
                await Context.Complaints.AddAsync(Complaint);
                await Context.SaveChangesAsync();

                return Redirect("./Complaints");
            }
            return Page();
        }
    }
}

MSSProject.Web/Areas/Core/Pages/User/CreateMeeting.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MSSProject.Data.Models;
using MSSProject.Web.Areas.Core.Data;
using MSSProject.Web.Areas.Identity.Data;
using MSSProject.Web.Data;
using MSSProject.Web.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;

namespace MSSProject.Web.Areas.Core.Pages.User
{
    public class CreateMeetingModel : DI_BasePageModel
    {
        public CreateMeetingModel(MSSCoreDbContext context,
           IAuthorizationService authorizationService,
           UserManager<MSSWebUser> userManager,
           RoleManager<IdentityRole> roleManager,
           MSSWebAuthContext authContext) : base(context,
                                                         authorizationService,
                                                         userManager,
                                                         roleManager,
                                                         authContext)
        { }
        [BindProperty]
        public Meeting Meeting { get; set; }
        [BindProperty]
        public PaymentInfo Payment { get; set; }
        public IList<PaymentInfo> PaymentList { get; set; }
        public List<PaymentInfo> UserPayList { get; set; } = new List<PaymentInfo>();

        [BindProperty]
        public IList<MSSWebUser> UserList { get; set; }
        [BindProperty]
        public IList<Room> RoomList { get; set; }

        [BindProperty]
        public int SelectedRoom { get; set; }

        [BindProperty]
        public List<Participant> SelectedList { get; set; } = new List<Participant>();

        [BindProperty]
        public InputModel Input { get; set; }
        public class InputModel
        {
            [Required]
            public int SelectedRoom { get; set; }
            [Required]
            public DateTime MeetDateTime { get; set; }

            public SpecialRoom SpecialRoom { get; set; }

            public List<Participant> ParticipantList { get; set; }
            public PaymentInfo PaymentMethod { get; set; }
        }
        public async Task<IActionResult> OnGetAsync()
        {
            PaymentList = await Context.Payments
                .AsNoTracking()
                .ToListAsync();
            UserList = await AuthContext.Users
                .AsNoTracking()
                .ToListAsync();
            RoomList = await Context.Rooms
                .AsNoTracking()
                .ToListAsync();

            var user = await UserManager.GetUserAsync(HttpContext.User);

            foreach (var payment in PaymentList)
            {
                if (user.UserName == payment.OwnerId)
                {
                    UserPayList.Add(payment);
                }
            }

            return Page();
        }
        public async Task<IActionResult> OnPostCreateMeetingAsync()
        {
            var user = await UserManager.GetUserAsync(HttpContext.User);
            var room = Context.Rooms.Find(SelectedRoom);

            if (ModelState.IsValid)
            {
                Meeting = new Meeting
                {
                    OwnerId = user.UserName,
                    RoomId = room.RoomId,
                    MeetDateTime = Input.MeetDateTime,
                    SpecialRoom = room.SpecialRoom,
                    //ParticipantList = SelectedList
                };
                await Context.Meetings.AddAsync(Meeting);
                await Context.SaveChangesAsync();
                return Redirect("./Meetings");
            }
            return Page();
        }

    }
}

MSSProject.Web/Areas/Core/Pages/User/CreatePayment.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MSSProject.Data.Models;
using MSSProject.Web.Areas.Core.Data;
using MSSProject.Web.Areas.Identity.Data;
using MSSProject.Web.Data;
using System;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;

namespace MSSProject.Web.Areas.Core.Pages.User
{
    [Authorize]
    public class CreatePaymentModel : DI_BasePageModel
    {
        public CreatePaymentModel(MSSCoreDbContext context,
           IAuthorizationService authorizationService,
           UserManager<MSSWebUser> userManager,
           RoleManager<IdentityRole> roleManager,
           MSSWebAuthContext authContext) : base(context,
                                                         authorizationService,
                                                         userManager,
                                                         roleManager,
                                                         authContext)
        { }
        [BindProperty]
        public PaymentInfo PaymentInfo { get; set; }
        [BindProperty]
        public InputModel Input { get; set; }
        public class InputModel
        {
            [Required]
            [RegularExpression("^[a-zA-Z]+$",
                ErrorMessage = "Please enter valid letters and punctuation.")]
            public string FirstName { get; set; }

            [Required]
            [RegularExpression("^[a-zA-Z]+$",
                ErrorMessage = "Please enter valid letters and punctuation.")]
            public string LastName { get; set; }

            [Required]
            [StringLength(16, ErrorMessage = "Card number must be sixteen digits.", MinimumLength = 16)]
            public string CardNumber { get; set; }

            [Required]
            public string CardType { get; set; }

            [Required]
            [StringLength(4, ErrorMessage = "Only three or four digits allowed.", MinimumLength = 3)]
            public string Cvv { get; set; }

            [Required]
            public DateTime ExpirationDate { get; set; }

            [Required]
            [StringLength(5, ErrorMessage = "Zip code must be five digits.", MinimumLength = 5)]
            public string BillingZipCode { get; set; }
        }
        public async Task<IActionResult> OnPostCreatePaymentAsync()
        {
            var user = await UserManager.GetUserAsync(HttpContext.User);
            if (ModelState.IsValid)
            {
                PaymentInfo = new PaymentInfo
                {
                    OwnerId = user.UserName,
                    FirstName = Input.FirstName,
                    LastName = Input.LastName,
                    CardNumber = Input.CardNumber,
                    CardType = Input.CardType,
                    Cvv = Input.Cvv,
                    ExpirationDate = Input.ExpirationDate,
                    BillingZipCode = Input.BillingZipCode
                };
                await Context.Payments.AddAsync(PaymentInfo);
                await Context.SaveChangesAsync();

                return Redirect("./PaymentInfo");
            }
            return Page();
        }
    }
}

MSSProject.Web/Areas/Core/Pages/User/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MSSProject.Web.Areas.Core.Pages.User
{
    [Authorize]
    //[Authorize(Roles = "User")]
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

MSSProject.Web/Areas/Core/Pages/User/Meetings.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MSSProject.Data.Models;
using MSSProject.Web.Areas.Core.Data;
using MSSProject.Web.Areas.Identity.Data;
using MSSProject.Web.Data;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace MSSProject.Web.Areas.Core.Pages.User
{
    [Authorize]
    public class MeetingsModel : DI_BasePageModel
    {
        public MeetingsModel(MSSCoreDbContext context,
           IAuthorizationService authorizationService,
           UserManager<MSSWebUser> userManager,
           RoleManager<IdentityRole> roleManager,
           MSSWebAuthContext authContext) : base(context,
                                                         authorizationService,
                                                         userManager,
                                                         roleManager,
                                                         authContext)
        { }
        [BindProperty]
        public Meeting Meeting { get; set; }
        [BindProperty]
        public IList<Room> RoomList { get; set; }
        [BindProperty]
        public IList<Meeting> MeetingList { get; set; }
        [BindProperty]
        public IList<MSSWebUser> UserList { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            UserList = await AuthContext.Users
                .AsNoTracking()
                .ToListAsync();
            MeetingList = await Context.Meetings
                .AsNoTracking()
                .ToListAsync();

            return Page();
        }

        public async Task<IActionResult> OnPostDeleteMeeting(int meetId)
        {
            Meeting = await Context.Meetings.FindAsync(meetId);
            Context.Meetings.Remove(Meeting);
            await Context.SaveChangesAsync();

            return Redirect("./Meetings");
        }
    }
}

MSSProject.Web/Areas/Core/Pages/User/PaymentInfo.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MSSProject.Data.Models;
using MSSProject.Web.Areas.Core.Data;
using MSSProject.Web.Areas.Identity.Data;
using MSSProject.Web.Data;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace MSSProject.Web.Areas.Core.Pages.User
{
    [Authorize]
    public class PaymentInfoModel : DI_BasePageModel
    {
        public PaymentInfoModel(MSSCoreDbContext context,
           IAuthorizationService authorizationService,
           UserManager<MSSWebUser> userManager,
           RoleManager<IdentityRole> roleManager,
           MSSWebAuthContext authContext) : base(context,
                                                         authorizationService,
                                                         userManager,
                                                         roleManager,
                                                         authContext)
        { }
        [BindProperty]
        public PaymentInfo PaymentInfo { get; set; }
        [BindProperty]
        public IList<PaymentInfo> PaymentList { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            PaymentList = await Context.Payments
                .AsNoTracking()
                .ToListAsync();
            return Page();
        }

        public async Task<IActionResult> OnPostDeleteAsync(int payId)
        {
            PaymentInfo = await Context.Payments.FindAsync(payId);
            Context.Payments.Remove(PaymentInfo);
            await Context.SaveChangesAsync();

            return Redirect("./PaymentInfo");
        }
    }
}

MSSProject.Web/Areas/Core/Pages/User/AdminFunctions.cshtml
@page
@model MSSProject.Web.Areas.Core.Pages.User.AdminFunctionsModel
@{
    ViewData["Title"] = "Navigate to Administrator Functions";
    ViewData["ActivePage"] = UserHubNavPages.AdminFunctions;
}

<h4 class="mt-4 text-center mx-auto">@ViewData["Title"]</h4>

<div class="shadow p-4 mb-4 text-center w-50 rounded-pill mx-auto background_col_1">
    <a id="manage" class="nav-link btn btn-link mx-auto rounded-pill w-75 " asp-area="Admin" asp-page="/AdminUser/Index" title="Admin Hub">Admininstrator Functions</a>
</div>

MSSProject.Web/Areas/Core/Pages/User/Complaints.cshtml
@page
@using Microsoft.AspNetCore.Identity
@using MSSProject.Web.Areas.Identity.Data
@model MSSProject.Web.Areas.Core.Pages.User.ComplaintsModel
@{
    ViewData["Title"] = "View and Create Complaints";
    ViewData["ActivePage"] = UserHubNavPages.Complaints;
}
@inject UserManager<MSSWebUser> UserManager

<h4 class="text-center mb-3">@ViewData["Title"]</h4>

<div class="container rounded shadow-lg p-2" style="background-color:#185895">
    <h3 class="text-center" style="color:white">Create New Complaint</h3>
</div>
<div class="container rounded shadow-lg p-2 mt-3" style="background-color:#185895">
    <div class="form-group">
        <form class="text-center" asp-page-handler="createcomplaint" method="post">
            <label style="font-weight:bold; color:white">Type Your Complaint Here</label>
            <textarea asp-for="Input.ComplaintText" class="form-control" rows="2"> </textarea>
            <label class="text-left">300 Characters Max</label><br />
            <span asp-validation-for="Input.ComplaintText" class="text-danger"></span>
            <button type="submit" class="btn m-1 w-50">Submit Complaint</button>
        </form>
    </div>
</div>
<hr />
<div>
    @{if (Model.ComplaintList == null)
        {
            <div class="container rounded shadow-lg p-3 mt-3" style="background-color:#185895">
                <h3 class="text-center" style="color:white">You Have No Recorded Complaints</h3>
            </div>
        }
        else
        {
            <h3 class="text-center mb-3" style="color:white">Complaint History</h3>
            <table class="table-bordered w-100 text-center">
                <tr style="color: whitesmoke">
                    <th scope="col">Date Created</th>
                    <th scope="col">Complaint</th>
                    <th scope="col">Response</th>
                </tr>
                @foreach (var complaint in Model.ComplaintList)
                {
                    var currUser = await UserManager.GetUserAsync(HttpContext.User);
                    if (currUser.Email == complaint.CreatorEmail)
                    {
                        <tr style="background-color: #185895; color:white">
                            <td>@Html.Encode(complaint.DateCreated)</td>
                            <td>@Html.Encode(complaint.ComplaintText)</td>
                            @if (complaint.Response == null)
                            {
                                <td>Awaiting Response</td>
                            }
                            else
                            {
                                <td>@Html.Encode(complaint.Response)</td>
                            }
                        </tr>
                    }
                }
            </table>
        }
    }
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

MSSProject.Web/Areas/Core/Pages/User/CreateMeeting.cshtml
@page
@model MSSProject.Web.Areas.Core.Pages.User.CreateMeetingModel
@{
    ViewData["Title"] = "Schedule Meeting";
    ViewData["ActivePage"] = UserHubNavPages.CreateMeeting;
}

<h4 class="text-center mb-3">@ViewData["Title"]</h4>

<div class="container rounded shadow-lg p-3" style="background-color:#185895">
    <form asp-page-handler="createmeeting" method="post">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-row m-4">
            <div class="col m-2">
                <label style="color:white; font-weight:bold">Choose Room</label>
                <select required name="selectedroom" class="form-control" id="selectedroom">
                    <option>Select Room</option>
                    @foreach (var room in Model.RoomList)
                    {
                        @if (room.Availability == MSSProject.Data.Models.Availability.Available)
                        {
                            @if (room.SpecialRoom == MSSProject.Data.Models.SpecialRoom.Yes)
                            {
                                <option value="@room.RoomId">Special Room: @Html.Encode(room.RoomName) --- Cost: $@Html.Encode(room.Cost + 100)</option>
                            }
                            else
                            {
                                <option value="@room.RoomId">@Html.Encode(room.RoomName) --- Cost: $@Html.Encode(room.Cost) @Html.Encode(room.RoomId)</option>
                            }
                        }
                    }
                </select>
                <hr />
                <label style="color:white; font-weight:bold">Choose Date and Time</label>
                <input asp-for="Input.MeetDateTime" class="form-control" type="datetime-local" min="@DateTime.Now" step="1" />
                <span asp-validation-for="Input.MeetDateTime.Date" class="text-danger"></span>
                <hr />
                <label style="color:white; font-weight:bold">Choose Payment Method</label>
                <select required name="payment" class="form-control" id="payment">
                    @if (Model.UserPayList == null)
                    {
                        <option>No Payments On File</option>

                    }
                    else
                    {
                        <option>Payment Methods</option>
                        @foreach (var payment in Model.UserPayList)
                        {
                            <option value="@payment.PayId">@Html.Encode(payment.CardType) ending in ** @Html.Encode(String.Format(payment.CardNumber.Substring(payment.CardNumber.Length - 4)))</option>
                        }
                    }
                </select>
                
            </div>
            <div class="col m-2">
                <label style="color:white; font-weight:bold">Select Participants</label>
                <table name="selectedlist" class="table-bordered w-100 text-center" style="font-size:small">
                    <tr style="color:white">
                        <th scope="col">Name</th>
                        <th scope="col">Email</th>
                        <th scope="col">Select</th>
                    </tr>
                    @foreach (var user in Model.UserList)
                    {
                        <tr class="m-1" style="color:white">
                            <td>
                                <input type="hidden" name="UserList.Index" value="@user.Id" />
                                <input type="hidden" name="UserList[@user.Id].Id" value="@user.Id" />
                                @user.FirstName @user.LastName
                            </td>
                            <td>
                                @user.Email
                            </td>
                            <td><input type="checkbox" name="SelectedList[@user.FirstName @user.LastName].Select" value="true" /></td>
                        </tr>
                    }
                </table>
                <a class="btn w-100 mt-5 @UserHubNavPages.CreatePaymentNavClass(ViewContext)" asp-page="./CreatePayment">Add New Payment Method</a>
            </div>
        </div>
        <div class="form-row m-4">
            <div class="col m-2">
                <a class="btn w-100 @UserHubNavPages.MeetingsNavClass(ViewContext)" id="back" asp-page="./Meetings">Cancel</a>
            </div>
            <div class="col m-2">
                <button type="submit" class="btn w-100">Schedule Meeting</button>
            </div>
        </div>
    </form>
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

MSSProject.Web/Areas/Core/Pages/User/CreatePayment.cshtml
@page
@model MSSProject.Web.Areas.Core.Pages.User.CreatePaymentModel
@{
    ViewData["Title"] = "Create New Payment Method";
    ViewData["ActivePage"] = UserHubNavPages.CreatePayment;
}

<h4 class="text-center mb-3">@ViewData["Title"]</h4>

<div class="container rounded shadow-lg p-3" style="background-color:#185895">
    <form asp-page-handler="createpayment" method="post">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-row m-4">
            <div class="col m-2">
                <input asp-for="Input.FirstName" class="form-control" placeholder="First Name" />
                <span asp-validation-for="Input.FirstName" class="text-danger"></span>
            </div>
            <div class="col m-2">
                <input asp-for="Input.LastName" class="form-control" placeholder="Last Name" />
                <span asp-validation-for="Input.LastName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-row m-4">
            <div class="col m-2">
                <input asp-for="Input.CardNumber" class="form-control" type="number" placeholder="Card Number" />
                <span asp-validation-for="Input.CardNumber" class="text-danger"></span>
            </div>
            <div class="col m-2">
                <input asp-for="Input.Cvv" class="form-control" type="number" placeholder="CVV" />
                <span asp-validation-for="Input.Cvv" class="text-danger"></span>
            </div>
        </div>
        <div class="form-row m-4 text-center">
            <div class="col m-2">
                <select class="form-control" asp-for="Input.CardType" id="cardtype">
                    <option>Visa</option>
                    <option>Mastercard</option>
                    <option>AMEX</option>
                    <option>Debit</option>
                </select>
            </div>
            <div class="col m-2">
                <input asp-for="Input.ExpirationDate" class="form-control" type="month" min="@DateTime.Now" placeholder="MM/DD/YYYY" />
                <span asp-validation-for="Input.ExpirationDate.Date" class="text-danger"></span>
            </div>
        </div>
        <div class="form-row m-4">
            <div class="col m-2">
                <input asp-for="Input.BillingZipCode" class="form-control w-25" type="number" placeholder="Billing Zip Code" />
                <span asp-validation-for="Input.BillingZipCode" class="text-danger"></span>
            </div>
        </div>
        <div class="form-row m-4">
            <div class="col m-2">
                <a class="btn w-100 @UserHubNavPages.PaymentInfoNavClass(ViewContext)" id="back" asp-page="./PaymentInfo">Cancel</a>
            </div>
            <div class="col m-2">
                <button type="submit" class="btn w-100">Create Payment Method</button>
            </div>
        </div>
    </form>
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

MSSProject.Web/Areas/Core/Pages/User/Index.cshtml
@page
@model MSSProject.Web.Areas.Core.Pages.User.IndexModel
@{
    ViewData["Title"] = "User Hub";
    ViewData["ActivePage"] = UserHubNavPages.Index;
}



<div class="text-center col-lg">
    <img src="~/images/MainLogo_Trans.png" alt="PennStateSoft" />
</div>

MSSProject.Web/Areas/Core/Pages/User/Meetings.cshtml
@page
@using Microsoft.AspNetCore.Identity
@using MSSProject.Web.Areas.Identity.Data
@model MSSProject.Web.Areas.Core.Pages.User.MeetingsModel
@{
    ViewData["Title"] = "Meetings";
    ViewData["ActivePage"] = UserHubNavPages.Meetings;
}
@inject UserManager<MSSWebUser> UserManager
@inject MSSCoreDbContext dbContext

<h4 class="text-center">@ViewData["Title"]</h4>
<hr />
<div>
    @if (Model.MeetingList == null)
    {
        <div class="container rounded shadow-lg p-3 mt-3" style="background-color:#185895">
            <h3 class="text-center" style="color:white">No Meetings Scheduled</h3>
        </div>
    }
    else
    {
        <h3 class="text-center mb-3" style="color:white">Current Meetings Scheduled</h3>
        <table class="table-bordered w-100 text-center">
            <tr style="color:white">
                <th scope="col">Date and Time</th>
                <th scope="col">Room</th>
                <th scope="col">Special Room</th>
                <th scope="col">Cost</th>
                <th scope="col">Participants</th>
                <th scope="col">Options</th>
            </tr>
            @foreach (var meeting in Model.MeetingList)
            {
                var currUser = await UserManager.GetUserAsync(HttpContext.User);
                var room = dbContext.Rooms.Find(meeting.RoomId);
                if (currUser.UserName == meeting.OwnerId)
                {
                    <tr style="background-color: #185895; color:white">
                        <td>@Html.Encode(meeting.MeetDateTime)</td>
                        <td>@Html.Encode(room.RoomName)</td>
                        <td>@Html.Encode(room.SpecialRoom)</td>
                        <td>$@Html.Encode(room.Cost)</td>
                        @{
                            if (meeting.ParticipantList == null)
                            {
                                <td>No Participants</td>
                            }
                            else
                            {
                                foreach (var participant in meeting.ParticipantList)
                                {
                                    <td>@Html.Encode(participant)</td>
                                }
                            }
                        }
                        <td>
                            <form asp-page-handler="deletemeeting" method="post">
                                <button type="submit" class="btn m-1">Delete</button>
                                <input type="hidden" name="meetId" value="@meeting.MeetId" />
                            </form>
                        </td>
                    </tr>
                }
            }
        </table>
    }
    <hr />
    <div class="text-center">
        <a class="btn w-25 @UserHubNavPages.CreateMeetingNavClass(ViewContext)" id="createmeeting" asp-page="./CreateMeeting">Schedule Meeting</a>
    </div>

</div>

MSSProject.Web/Areas/Core/Pages/User/_UserHubNav.cshtml
@using Microsoft.AspNetCore.Identity
@using MSSProject.Web.Areas.Identity.Data

@inject UserManager<MSSWebUser> UserManager


<ul class="nav nav-pills flex-column mt-5">
    <li class="nav-item">
        <a class="nav-link @UserHubNavPages.IndexNavClass(ViewContext)" id="userhub" asp-page="./Index">User Hub</a>
    </li>
    <li class="nav-item">
        <a class="nav-link @UserHubNavPages.MeetingsNavClass(ViewContext)" id="meetings" asp-page="./Meetings">Manage Meetings</a>
    </li>
    <li class="nav-item">
        <a class="nav-link @UserHubNavPages.ComplaintsNavClass(ViewContext)" id="complaints" asp-page="./Complaints">Lodge Complaint</a>
    </li>
    <li class="nav-item">
        <a class="nav-link @UserHubNavPages.PaymentInfoNavClass(ViewContext)" id="paymentinfo" asp-page="./PaymentInfo">Payment Information</a>
    </li>
    @if (User.IsInRole("Administrator") == true)
    {
        <li class="nav-item">
            <a class="nav-link @UserHubNavPages.AdminFunctionsNavClass(ViewContext)" id="adminfunctions" asp-page="./AdminFunctions">Administrator Functions</a>
        </li>
    }
</ul>